version: '3'
services:
  localdb:
    build: docker/localdb
    image: localdb
  jupyter:
    image: aneel/internal-displacement-jupyter:no-spacy
    command: sh -c "jupyter notebook --no-browser --ip=0.0.0.0 --port 3323 /internal-displacement/notebooks"
    stdin_open: true
    tty: true
    volumes:
      - .:/internal-displacement
    ports:
      - "3323:3323"
    depends_on:
      - localdb
    env_file: docker.env
  nodejs:
    build: internal-displacement-web
    image: internal-displacement-web
    volumes:
      # client
      - ./internal-displacement-web/client/public:/internal-displacement-web/client/public
      - ./internal-displacement-web/client/src:/internal-displacement-web/client/src
      - ./internal-displacement-web/client/package.json:/internal-displacement-web/client/package.json
      - ./internal-displacement-web/client/yarn.lock:/internal-displacement-web/client/yarn.lock
      # server
      - ./internal-displacement-web/server/api:/internal-displacement-web/server/api
      - ./internal-displacement-web/server/pgDB:/internal-displacement-web/server/pgDB
      - ./internal-displacement-web/server/public:/internal-displacement-web/server/public
      - ./internal-displacement-web/server/src:/internal-displacement-web/server/src
      - ./internal-displacement-web/server/index.js:/internal-displacement-web/server/index.js
      - ./internal-displacement-web/server/package.json:/internal-displacement-web/server/package.json
      - ./internal-displacement-web/server/routes.js:/internal-displacement-web/server/routes.js
      - ./internal-displacement-web/server/yarn.lock:/internal-displacement-web/server/yarn.lock
      # start
      - ./internal-displacement-web/package.json:/internal-displacement-web/package.json
      - ./internal-displacement-web/yarn.lock:/internal-displacement-web/yarn.lock
    ports:
      - "3000:3000"
      - "3322:3322"
    depends_on:
      - localdb
    env_file: docker.env
