version: '3'
services:
  jupyter:
    build: .
    image: internal-displacement
    command: sh -c "jupyter notebook --no-browser --ip=0.0.0.0 --port 3323 /internal-displacement/notebooks"
    stdin_open: true
    tty: true
    volumes:
      - .:/internal-displacement
    ports:
      - "3323:3323"
    env_file: production.env
  nodejs:
    build: internal-displacement-web
    image: internal-displacement-web
    volumes:
      - ./internal-displacement-web/src:/internal-displacement-web/src
      - ./internal-displacement-web/package.json:/internal-displacement-web/package.json
      - ./internal-displacement-web/index.html:/internal-displacement-web/index.html
    ports:
      - "3322:3322"
    env_file: production.env
  nginx:
    build: docker/nginx
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs
